// lib/buildInfo.ts — Atualizado automaticamente pelo smart-deploy.ps1
export const BUILD_INFO = {
  version: '5.0.0',
  buildTimestamp: '2026-02-08T12:32:34.404Z',
  commitHash: '5dcfc41',
  branch: 'master',
  changelog: [
    // ── v5.0.0 (MAJOR) ──
    'Anti-truncamento: Removidos TODOS os limites artificiais de tokens (maxOutputTokens) de síntese, follow-up e prompts',
    'Anti-truncamento: Detecção automática de truncamento via finishReason com aviso visual ao usuário',
    'Anti-truncamento: Timeout de síntese aumentado para ~5 min (290s) dentro do maxDuration Vercel',
    'UI: Menu de config unificado com 5 abas (Geral, Pipeline, PRO, TCC, Templates) direto no input principal',
    'UI: Tab Pipeline com seletores de modelo por fase (Decomposição, Avaliação, Síntese) + config de fontes Auto/Manual',
    'UI: Tab TCC com ativação one-click que configura automaticamente ABNT, citações acadêmicas e profundidade exaustiva',
    'UI: Formulário de metadados TCC (título, autor, instituição, curso, orientador, cidade, ano, mín. fontes)',
    'TCC: Modo de pesquisa "Trabalho de Conclusão de Curso" com prompt ABNT completo (NBR 14724:2024)',
    'TCC: Estrutura obrigatória: Capa, Folha de Rosto, Resumo/Abstract, Sumário, Introdução, Ref. Teórico, Metodologia, Resultados, Conclusão, Referências',
    'TCC: Citações ABNT automáticas (direta curta/longa, indireta, apud, múltiplos autores)',
    'Multi-seção: Outline estruturado via generateObject antes da síntese',
    'Multi-seção: Streaming por seção com contexto acumulado entre seções (anti-truncamento arquitetural)',
    'Multi-seção: Ativação automática para modo TCC e detailLevel=exhaustive com >10 fontes',
    'CrossRef: Validação de citações acadêmicas via CrossRef API (gratuita, sem API key)',
    'CrossRef: Extração de citações ABNT e inline + verificação contra base de dados acadêmica',
    'CrossRef: Relatório de verificação com status (verificada/inconclusiva/não encontrada) e DOI',
    'Legibilidade: Métricas pós-geração via text-readability-ts (Flesch, Kincaid, Gunning Fog, SMOG, Coleman-Liau, ARI)',
    'Legibilidade: Card de métricas com contagem de palavras, frases, vocabulário único e tempo de leitura',
    'SSE: Eventos de progresso por seção durante síntese multi-seção',
    'SSE: UI de progresso com status individual por seção (pending/generating/complete/error)',
    'DOCX: Exportação nativa via docx npm com parsing de Markdown (headings, bold, italic, code, tabelas, bullets, blockquotes)',
    'DOCX: Citações em superscript colorido, tabelas com bordas, formatação de título e metadados',

    // ── v4.1.1 (PATCH) ──
    'UI: Dropdown do seletor de modelo no chat não é mais coberto pelas mensagens (z-index fix)',
    'UI: Header do chat com z-20 para stacking context correto sobre a área de mensagens',
    'UI: Padding do input de pesquisa aumentado para pr-52 (208px) — botões não sobrepõem mais o texto',

    // ── v4.1.0 (MINOR) ──
    'Branding: App renomeado para Âmago.AI em toda a aplicação (header, exports, metadata, testes)',
    'UI: Botão "Pesquisar" não sobrepõe mais elementos no input (padding corrigido)',
    'Safety: Configurações de segurança permissivas (BLOCK_NONE) aplicadas automaticamente para modelos Google em todas as 10 chamadas LLM',
    'Safety: Módulo config/safety-settings.ts com documentação de status por provedor (Google, Anthropic, OpenAI, etc.)',
    'Safety: Integração centralizada via getSafetyProviderOptions() — sem necessidade de config manual por rota',

    // ── v4.0.0 (MAJOR) ──
    'Chat: Nova seção "Pergunte à IA" — interface de chat conversacional com streaming palavra-a-palavra',
    'Chat: Sidebar colapsável com lista de conversas agrupadas por data, busca, renomear, exportar e excluir',
    'Chat: Seletor de modelo inline com todos os modelos de texto do AI Gateway (sem embeddings/geradores de imagem)',
    'Chat: Detecção automática de artifacts (<artifact>) no stream com integração ao ArtifactsPanel existente',
    'Chat: Anexação de arquivos com extração de texto (txt, md, csv, json, código) + Ctrl+V para imagens',
    'Chat: Persistência de conversas via IndexedDB (Dexie v3) com auto-save após cada resposta',
    'Chat: Exportação de conversas como Markdown',
    'Chat: System prompt configurável nas Settings com suporte a artifacts automáticos',
    'Chat: Sugestões de prompt na tela inicial (4 exemplos interativos)',
    'Nav: "Pergunte à IA" como primeiro item na topbar, "Pesquisa" renomeada para "Pesquisa Profunda"',
    'Nav: CommandMenu (Ctrl+K) atualizado com atalho para chat',
    'Settings: Nova seção "Chat" com modelo padrão e prompt de sistema customizável',
    'API: Nova rota /api/chat com streamText via Vercel AI Gateway',

    // ── v3.2.0 (MINOR) ──
    'Pipeline: Sistema de 3 modos de processamento — Base (single-pass), Extended (Map-Reduce), Ultra (Iterativo + Verificação)',
    'Pipeline: Resolução automática de modo baseada no modelo e quantidade de fontes configuradas',
    'Pipeline: Map-Reduce paralelo com batches via Promise.all para processamento de grandes volumes de fontes',
    'Pipeline: Enriquecimento iterativo com fontes remanescentes no modo Ultra',
    'Pipeline: Verificação cruzada obrigatória de afirmações factuais no modo Ultra',
    'Config: Mapa de limites de fontes para 130+ modelos com margens de segurança de 15%',
    'Config: System prompts especializados para MAP, REDUCE, ENRICH e VERIFY',
    'UI: Sliders dinâmicos de fontes com limites máximos baseados no modelo de síntese selecionado',
    'UI: Badge colorido de modo de processamento (Direto/Map-Reduce/Iterativo) com custo e latência estimados',
    'UI: Progresso granular no ResearchProgress — sub-estágios MAP, REDUCE, ENRICH, VERIFY visíveis quando ativos',
    'Testes: 31 novos testes unitários para model-source-limits e pipeline-prompts',

    // ── v3.1.0 (MINOR) ──
    'Upload: Sistema universal de anexação de arquivos e imagens (UniversalAttachment)',
    'Upload: Processadores para imagem (thumbnail+resize+base64), PDF (extração de texto), CSV (parse+preview), JSON, texto',
    'Upload: Botão 📎 no ResearchInput com Ctrl+V para colar imagens do clipboard',
    'Upload: Drag-and-drop global com overlay visual e dropzone dedicada',
    'Upload: Chips de preview com thumbnail, nome, tamanho e botão remover',
    'Upload: Validação de tipo MIME, tamanho, wildcards e anti-duplicatas',
    'Upload: Context builder injeta conteúdo extraído no prompt de síntese automaticamente',
    'Upload: Pipeline completo: ResearchInput → page → useResearch → TaskManager → API → Pipeline → Synthesizer',
    'Upload: Integração no Generate com dropzone + seletor de propósito (Referência/Modificar/Analisar/Contexto)',
    'Upload: Ícones de tipo de arquivo coloridos (PDF vermelho, CSV verde, JSON amarelo, etc)',
    'Upload: 31 testes unitários cobrindo mimeTypes, fileProcessors, contextBuilder e configs',

    // ── v3.0.0 (MAJOR) ──
    'PRO: Seletor de estilo de escrita (5 estilos com preview inline)',
    'PRO: Controle de nível de detalhe (4 níveis com estimativa de páginas/tempo)',
    'PRO: Idioma de raciocínio interno (PT/EN/Auto/Bilíngue) com tooltip explicativo',
    'PRO: Seletor de formato de citação (6 formatos: Inline, Footnotes, APA7, ABNT, IEEE, Vancouver)',
    'PRO: Framework de avaliação de fontes (CRAAP/SIFT/RADAR/Custom) com dimensões',
    'PRO: 6 modos de pesquisa (Padrão, Comparativo, Temporal, Contrário, Meta-análise, Fact-check)',
    'PRO: Seções customizáveis do relatório (toggle + reordenação por teclado + obrigatórias)',
    'PRO: Filtros avançados (recência, tipos de fonte, idiomas, allowlist/blocklist de domínios)',
    'PRO: 6 formatos de exportação (Markdown, PDF, Slides, Podcast, Thread Social, JSON)',
    'PRO: Templates salvos com busca, favoritos e categorias',
    'PRO: ExportModal com preview e download direto',
    'PRO: Integração completa com prompt de síntese (estilo, detalhe, citação, modo)',
    'PRO: Painel PRO integrado em ResearchInput e Settings',

    // ── v2.0.1 (PATCH) ──
    'Fix: modelo inexistente google/imagen-4.0-fast-generate-001 removido do catálogo',
    'Fix: import generateImage → experimental_generateImage (AI SDK 6.x)',
    'Fix: image-only models agora usam aspectRatio em vez de size',
    'Fix: novos modelos bfl/flux-2-pro e bfl/flux-2-flex adicionados',
    'Fix: logs com timestamp completo (dd/mm hh:mm:ss), ordenação cronológica correta',
    'Fix: botão copiar logs filtrados + copiar todos separados',
    'Fix: Ctrl+A scoped funcional via document.activeElement',

    // ── v2.0.0 (MAJOR) ──
    'Sprint 1: Textarea progressivo auto-resize + config piso/teto de fontes (auto/manual)',
    'Sprint 2: Biblioteca 3 abas (Pesquisas/Imagens/Prompts) + auto-save IndexedDB v2 + bulk ops',
    'Sprint 3: Organização por IA da biblioteca + chat pós-pesquisa multi-turno persistente',
    'Sprint 4: Recomendação inteligente de modelos (3 tiers + calculadora IA via Gemini 2.5 Flash)',
    'Sprint 5: Prompt Reverso PRO (10 categorias) + checklist verificado + correção automática',
    'Sprint 6: Relatório final de avaliação com notas segmentadas',

    // ── v1.0.0 (MAJOR) ──
    'UI/UX Overhaul completo (10 fases)',
    'FASE 1: Design tokens OKLCH semânticos, glassmorphism utilities, Sonner toasts',
    'FASE 2: Command Palette global (Ctrl+K) com navegação e pesquisas recentes',
    'FASE 3: ReasoningBlock — cadeia de raciocínio colapsável com BrainCircuit',
    'FASE 4: Progressive disclosure no input de pesquisa',
    'FASE 5: Report Viewer tipografia otimizada (65ch), citation badges circulares',
    'FASE 6: nuqs URL state na Biblioteca (q, fav, depth params)',
    'FASE 7: Artifacts Panel resizável com drag handle (320-900px)',
    'FASE 8: Skeleton shimmer + optimistic UI com undo toast',
    'FASE 9: Acessibilidade (skip-to-content, aria-current, aria-expanded, reduced-motion)',
    'FASE 10: Polimento (focus-visible rings, fade-in animations)',
    'Fix: geração de imagem — statusCode < 400 forçado a 500, validação bytes vazios',
  ],
  previousVersion: '4.1.1',
};